export default function CreatePage() {
      return (
          <main
                className="container"
                      style={{
                              minHeight: "100vh",
                                      display: "flex",
                                              justifyContent: "center",
                                                      alignItems: "center",
                                                              padding: "100px 20px",
                                                                    }}
                                                                        >
                                                                              <div
                                                                                      className="glass"
                                                                                              style={{
                                                                                                        width: "100%",
                                                                                                                  maxWidth: "900px",
                                                                                                                            padding: "50px",
                                                                                                                                      borderRadius: "28px",
                                                                                                                                                textAlign: "center",
                                                                                                                                                        }}
                                                                                                                                                              >
                                                                                                                                                                      <p
                                                                                                                                                                                style={{
                                                                                                                                                                                            color: "#38bdf8",
                                                                                                                                                                                                        letterSpacing: "2px",
                                                                                                                                                                                                                    fontWeight: 600,
                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                CREATE A STARLIGHT
                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                <h1
                                                                                                                                                                                                                                                                          className="gradient-text"
                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                fontSize: "3rem",
                                                                                                                                                                                                                                                                                                            margin: "20px 0",
                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                        Let's Create Something Magical ✨
                                                                                                                                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                                                                                                                                        <p
                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                              color: "#cbd5e1",
                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: "40px",
                                                                                                                                                                                                                                                                                                                                                                                                      lineHeight: 1.8,
                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                  This wizard will guide you step by step to create an unforgettable
                                                                                                                                                                                                                                                                                                                                                                                                                                            celebration experience.
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="primary-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Start Creating →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
