const celebrations = [
      { emoji: "🎂", title: "Birthday" },
        { emoji: "❤️", title: "Anniversary" },
          { emoji: "🎓", title: "Graduation" },
            { emoji: "💍", title: "Wedding" },
              { emoji: "🎉", title: "Other" },
              ];

              export default function WelcomeStep() {
                return (
                    <>
                          <h2
                                  style={{
                                            fontSize: "2.5rem",
                                                      marginBottom: "15px",
                                                              }}
                                                                    >
                                                                            Who are you celebrating?
                                                                                  </h2>

                                                                                        <p
                                                                                                style={{
                                                                                                          color: "#cbd5e1",
                                                                                                                    marginBottom: "40px",
                                                                                                                            }}
                                                                                                                                  >
                                                                                                                                          Choose the type of celebration.
                                                                                                                                                </p>

                                                                                                                                                      <div
                                                                                                                                                              style={{
                                                                                                                                                                        display: "grid",
                                                                                                                                                                                  gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))",
                                                                                                                                                                                            gap: "20px",
                                                                                                                                                                                                    }}
                                                                                                                                                                                                          >
                                                                                                                                                                                                                  {celebrations.map((item) => (
                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                        key={item.title}
                                                                                                                                                                                                                                                    className="glass"
                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                              padding: "30px",
                                                                                                                                                                                                                                                                                            borderRadius: "20px",
                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                        background: "rgba(255,255,255,.05)",
                                                                                                                                                                                                                                                                                                                                      border: "1px solid rgba(255,255,255,.08)",
                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: "3rem" }}>
                                                                                                                                                                                                                                                                                                                                                                                      {item.emoji}
                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                              <h3
                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {item.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }