"use client";

import { useState } from "react";

export default function GiftBox() {
  const [opened, setOpened] = useState(false);

    return (
        <div
              style={{
                      marginTop: "40px",
                              textAlign: "center",
                                    }}
                                        >
                                              {!opened ? (
                                                      <>
                                                                <div
                                                                            onClick={() => setOpened(true)}
                                                                                        style={{
                                                                                                      fontSize: "6rem",
                                                                                                                    cursor: "pointer",
                                                                                                                                  transition: "0.3s",
                                                                                                                                              }}
                                                                                                                                                        >
                                                                                                                                                                    🎁
                                                                                                                                                                              </div>

                                                                                                                                                                                        <p
                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                  color: "#cbd5e1",
                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                    Tap the gift to open it
                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                        fontSize: "5rem",
                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                          🎂🎈🎉
                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                              <h2
                                                                                                                                                                                                                                                                                                                                                                                          className="gradient-text"
                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Surprise! 🎉
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "#cbd5e1",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Wishing you endless happiness,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  success and unforgettable memories.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }