"use client";

import { useState } from "react";

export default function Letter() {
  const [opened, setOpened] = useState(false);

    return (
        <div
              style={{
                      marginTop: "50px",
                              textAlign: "center",
                                    }}
                                        >
                                              {!opened ? (
                                                      <>
                                                                <div
                                                                            onClick={() => setOpened(true)}
                                                                                        style={{
                                                                                                      fontSize: "5rem",
                                                                                                                    cursor: "pointer",
                                                                                                                                }}
                                                                                                                                          >
                                                                                                                                                      💌
                                                                                                                                                                </div>

                                                                                                                                                                          <p
                                                                                                                                                                                      style={{
                                                                                                                                                                                                    color: "#94a3b8",
                                                                                                                                                                                                                }}
                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                      Tap to open your letter
                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                className="glass"
                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                      padding: "30px",
                                                                                                                                                                                                                                                                                                                  borderRadius: "24px",
                                                                                                                                                                                                                                                                                                                              marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                          <h2>Dear Friend ❤️</h2>

                                                                                                                                                                                                                                                                                                                                                                    <p
                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                              lineHeight: 1.8,
                                                                                                                                                                                                                                                                                                                                                                                                            color: "#cbd5e1",
                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                              Today is your special day.
                                                                                                                                                                                                                                                                                                                                                                                                                                                          May your life always be filled with happiness,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      love, laughter and unforgettable memories.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Thank you for being an amazing person.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Happy Birthday! 🎂🎉
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }